server:
 port: 8083

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      username: root
      password: 123456
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 5000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 20000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1
          merge-sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


logging:
 level:
   root: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
